on:
  push:
  pull_request:

name: CI

jobs:
  R-CMD-check:
    name: (R ${{ matrix.version }} - ${{ matrix.os }})
    strategy:
      matrix:
        version:
          - 'release'
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install binary dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        env:
          AECONOMICA_TEST_KEY: ${{ secrets.AECONOMICA_TEST_KEY }} # API key for aeconomica

      - name: Test coverage
        if: matrix.os == 'ubuntu-latest' && matrix.version == 'release'
        run: |
          remotes::install_cran("covr")
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
        env:
          AECONOMICA_TEST_KEY: ${{ secrets.AECONOMICA_TEST_KEY }} # API key for aeconomica

  pkgdown:
    needs: R-CMD-check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install binary dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
